services:
  cms:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
      args:
        DATABASE_URL: ${DATABASE_URL}
        PAYLOAD_SECRET: ${PAYLOAD_SECRET}
    ports:
      - '3000:3000'
    environment:
      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM_ADDRESS: ${SMTP_FROM_ADDRESS}
    develop:
      watch:
        - path: ./src
          target: /app
          action: sync
          ignore:
            - node_modules/
        - path: ./package.json
          action: rebuild
